### ISSUE TITLE
Can't export designs that have a forward-slash in their name

### ISSUE THREAD

**Issue by thenickdude** [aconz2/Fusion360Exporter#1]
Designs with forward-slashes in their name (e.g. "Loc-line 1/2 inch cup") fail to export with this error message:

```
Visiting file Canon MT-24EX 1/2 inch Loc-line foot v10 . f3d
Opening Canon MT-24EX 1/2 inch Loc-line foot
Traceback (most recent call last):
  File "/Users/nick/Downloads/Fusion360Exporter-master/Exporter.py", line 125, in visit_file
    counter += export_file(ctx, format, file, doc)
  File "/Users/nick/Downloads/Fusion360Exporter-master/Exporter.py", line 103, in export_file
    options = em.createFusionArchiveExportOptions(str(output_path))
  File "/Users/nick/Library/Application Support/Autodesk/webdeploy/production/be6edacd6545d1f4fb1c9284e555a36b1cd1b40c/Autodesk Fusion 360.app/Contents/Api/Python/packages/adsk/fusion.py", line 11325, in createFusionArchiveExportOptions
    return _fusion.ExportManager_createFusionArchiveExportOptions(self, *args)
RuntimeError: 3 : The selected folder does not exist.
```

Maybe slashes could be replaced by "-" signs?

Thanks for writing this script, it's awesome!

**Comment by aconz2** [comment]
Should be fixed with https://github.com/aconz2/Fusion360Exporter/commit/2f3344ecd536fe42818f844ce5d93c055348019a

**Comment by thenickdude** [comment]
That fixed it, thanks!
