### ISSUE TITLE
SystemError: <built-in function delete_DataProjects> returned a result with an error set

### ISSUE THREAD

**Issue by progman32** [aconz2/Fusion360Exporter#4]
Trying to export all formats:
```
---------------------------
Fusion 360
---------------------------
Log file is at H:\Fusion360Export\2020_09_21_18_04.txt
Traceback (most recent call last):
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 232, in visit_folder
    counter += visit_file(new_ctx, file)
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 211, in visit_file
    doc.open()
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 63, in open
    self._document = self._ctx.app.documents.open(self._file)
  File "C:/Users/giacomo/AppData/Local/Autodesk/webdeploy/production/4143a7d9c7cd58a0f86968fd3809be3e34945ca1/Api/Python/packages\adsk\core.py", line 7295, in open
    return _core.Documents_open(self, *args)
RuntimeError: 3 : Failed to download file.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 235, in visit_folder
    counter += visit_folder(new_ctx, sub_folder)
SystemError: <built-in function delete_DataFiles> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 247, in main
    counter += visit_folder(ctx, project.rootFolder)
SystemError: <built-in function delete_DataFolders> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/giacomo/Desktop/Fusion360Exporter-master/Exporter.py", line 313, in notify
    counter = main(ctx)
SystemError: <built-in function delete_DataProjects> returned a result with an error set

---------------------------
OK   
---------------------------
```

**Comment by progman32** [comment]
Seems related to some image renders in the project. Deleted them and it got through the project.

**Comment by aconz2** [comment]
Okay I will make a note on the readme about image renders. There's obviously a bunch of things I can't easily test for so thanks for the report
